"""Novaforge — Remote Web Interface (Phase 2).

Exposes ArbiterAI and server status over HTTP so developers can interact
with Novaforge from any browser on the LAN (or remotely via ngrok).

Novaforge Phase 2 tasks
-----------------------
NF2-1   FastAPI endpoints: /ai/query, /ai/stream (SSE), /ai/actions,
        /ai/execute, /ai/theme, /ai/health, /ai/context/file, /ai/history.
NF2-2   Remote browser client — served at GET / as a self-contained dark-mode
        HTML application (no CDN dependencies, ChatGPT palette).
NF2-3   Clickable AI action buttons: browser calls /ai/execute with an
        action payload generated by the AI.
NF2-4   /ai/theme endpoint returns the current Novaforge colour palette as
        JSON for frontend use.
NF2-5   Bearer token authentication: a token is auto-generated on first
        startup and written to .novaforge_api_token.  All state-changing
        endpoints require ``Authorization: Bearer <token>``.
NF2-6   LAN / remote access: server binds to 0.0.0.0 so any machine on the
        LAN can reach it.  Run with ``--ngrok`` to open a public tunnel.
NF2-7   /ai/resources: live CPU / RAM / disk usage via psutil (graceful
        fallback if psutil is not installed).
NF2-8   Crash-protection supervisor: run this module with the ``--supervised``
        flag to wrap uvicorn in an auto-restart loop.

Quick start
-----------
    # Normal (LAN access, port 8006):
    python -m Projects.Novaforge.WebAPI.remote_api

    # Supervised (auto-restart on crash):
    python -m Projects.Novaforge.WebAPI.remote_api --supervised

    # With ngrok tunnel:
    python -m Projects.Novaforge.WebAPI.remote_api --ngrok
"""
from __future__ import annotations

import asyncio
import datetime
import json
import os
import pathlib
import secrets
import sys
import time
import threading
from typing import Any, AsyncGenerator

# ── FastAPI / Starlette imports ───────────────────────────────────────────────
try:
    from fastapi import FastAPI, HTTPException, Request, Depends
    from fastapi.responses import HTMLResponse, JSONResponse, StreamingResponse
    from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
    from pydantic import BaseModel
    import uvicorn
    _FASTAPI_OK = True
except ImportError:
    _FASTAPI_OK = False

# ── Optional psutil for resource monitoring (NF2-7) ──────────────────────────
try:
    import psutil as _psutil
    _PSUTIL_OK = True
except ImportError:
    _PSUTIL_OK = False

# ── Novaforge AI integration ──────────────────────────────────────────────────
_NF_ROOT = pathlib.Path(__file__).resolve().parent.parent  # Projects/Novaforge/
sys.path.insert(0, str(_NF_ROOT.parent.parent))           # repo root

try:
    from Projects.Novaforge.AI.arbiter_ai import ArbiterAIManager, AIAction
    _AI_OK = True
except ImportError:
    _AI_OK = False
    ArbiterAIManager = None  # type: ignore[misc,assignment]
    AIAction = None           # type: ignore[misc,assignment]

# =============================================================================
# NF2-5 — Token authentication
# =============================================================================

_TOKEN_FILE = _NF_ROOT / ".novaforge_api_token"


def _load_or_create_token() -> str:
    """Load the API token from disk, generating a new one if absent.

    NF2-5
    """
    if _TOKEN_FILE.exists():
        tok = _TOKEN_FILE.read_text(encoding="utf-8").strip()
        if tok:
            return tok
    tok = secrets.token_urlsafe(32)
    _TOKEN_FILE.write_text(tok + "\n", encoding="utf-8")
    _TOKEN_FILE.chmod(0o600)
    print(f"[Novaforge WebAPI] API token: {tok}")
    print(f"[Novaforge WebAPI] Token saved to: {_TOKEN_FILE}")
    return tok


_API_TOKEN: str = _load_or_create_token()


def _verify_token(
    creds: HTTPAuthorizationCredentials = Depends(HTTPBearer(auto_error=False)),
) -> None:
    """FastAPI dependency that enforces Bearer token auth.

    NF2-5
    """
    if creds is None or creds.credentials != _API_TOKEN:
        raise HTTPException(status_code=401, detail="Invalid or missing API token")


# =============================================================================
# NF2-4 — Theme palette
# =============================================================================

_THEME_CHATGPT: dict[str, str] = {
    "name":       "ChatGPT Dark",
    "bg":         "#202123",
    "panel":      "#343541",
    "card":       "#444654",
    "border":     "#565869",
    "accent":     "#10a37f",
    "accent2":    "#19c37d",
    "fg":         "#ececf1",
    "fg_dim":     "#8e8ea0",
    "danger":     "#ef4146",
    "warn":       "#e0a84d",
    "ok":         "#10a37f",
    "font":       '"Söhne", "ui-sans-serif", system-ui, sans-serif',
}

# =============================================================================
# NF2-2/3 — Embedded browser client (self-contained HTML, no CDN)
# =============================================================================

_DASHBOARD_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Novaforge — AI Dev Interface</title>
<style>
  *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
  :root{
    --bg:#202123;--panel:#343541;--card:#444654;--border:#565869;
    --accent:#10a37f;--accent2:#19c37d;--fg:#ececf1;--fg-dim:#8e8ea0;
    --danger:#ef4146;--warn:#e0a84d;--font:"Segoe UI",system-ui,sans-serif;
    --radius:8px;--shadow:0 2px 14px rgba(0,0,0,.5);
  }
  body{background:var(--bg);color:var(--fg);font-family:var(--font);min-height:100vh;display:flex;flex-direction:column}
  header{background:var(--panel);border-bottom:1px solid var(--border);padding:12px 20px;display:flex;align-items:center;gap:10px;position:sticky;top:0;z-index:100}
  header h1{font-size:1.1rem;font-weight:600}
  .badge{font-size:.7rem;background:var(--accent);color:#000;border-radius:4px;padding:2px 7px;font-weight:700}
  .dot{width:8px;height:8px;border-radius:50%;display:inline-block;background:var(--fg-dim)}
  .dot.ok{background:var(--accent)}.dot.err{background:var(--danger)}.dot.warn{background:var(--warn)}
  main{display:grid;grid-template-columns:1fr 320px;flex:1;min-height:0;height:calc(100vh - 52px)}
  /* ── Chat panel ── */
  #chat-pane{display:flex;flex-direction:column;border-right:1px solid var(--border)}
  #messages{flex:1;overflow-y:auto;padding:16px;display:flex;flex-direction:column;gap:12px}
  .msg{max-width:85%;padding:10px 14px;border-radius:var(--radius);font-size:.88rem;line-height:1.5;white-space:pre-wrap}
  .msg.user{background:var(--card);align-self:flex-end;border-bottom-right-radius:2px}
  .msg.ai{background:var(--panel);align-self:flex-start;border-bottom-left-radius:2px}
  .msg.system{background:#2a2c35;color:var(--fg-dim);font-size:.78rem;align-self:center;padding:6px 12px;border-radius:20px}
  .actions-row{display:flex;flex-wrap:wrap;gap:6px;padding:0 16px 10px}
  .action-btn{background:var(--panel);border:1px solid var(--accent);color:var(--accent);border-radius:var(--radius);padding:5px 12px;font-size:.78rem;cursor:pointer;transition:background .15s}
  .action-btn:hover{background:var(--accent);color:#000}
  #input-area{border-top:1px solid var(--border);padding:12px 16px;display:flex;gap:8px}
  #user-input{flex:1;background:var(--card);border:1px solid var(--border);color:var(--fg);border-radius:var(--radius);padding:9px 12px;font-size:.88rem;resize:none;height:42px}
  #user-input:focus{outline:none;border-color:var(--accent)}
  .send-btn{background:var(--accent);border:none;color:#000;border-radius:var(--radius);padding:9px 16px;font-size:.88rem;font-weight:600;cursor:pointer;transition:background .15s}
  .send-btn:hover{background:var(--accent2)}
  /* ── Right sidebar ── */
  #sidebar{background:var(--panel);overflow-y:auto;padding:14px}
  .sidebar-section{margin-bottom:18px}
  .sidebar-hdr{font-size:.72rem;font-weight:700;text-transform:uppercase;letter-spacing:.06em;color:var(--fg-dim);margin-bottom:8px;padding-bottom:6px;border-bottom:1px solid var(--border)}
  .stat-card{background:var(--card);border:1px solid var(--border);border-radius:var(--radius);padding:10px 12px;margin-bottom:6px}
  .stat-val{font-size:1.3rem;font-weight:700;color:var(--accent)}
  .stat-lbl{font-size:.7rem;color:var(--fg-dim);margin-top:2px}
  .resource-bar{background:var(--bg);border-radius:3px;height:6px;margin-top:5px}
  .resource-fill{height:6px;border-radius:3px;background:var(--accent);transition:width .4s}
  .server-card{background:var(--card);border:1px solid var(--border);border-radius:var(--radius);padding:9px 11px;margin-bottom:6px;font-size:.8rem}
  .server-name{font-weight:600;margin-bottom:3px}
  .tag{font-size:.68rem;background:var(--bg);border-radius:3px;padding:1px 5px;color:var(--fg-dim)}
  #auth-banner{background:#2d1f0f;border:1px solid var(--warn);border-radius:var(--radius);padding:9px 12px;margin-bottom:10px;font-size:.78rem;color:var(--warn);word-break:break-all}
  #theme-swatch{display:flex;flex-wrap:wrap;gap:4px;margin-top:6px}
  .swatch{width:22px;height:22px;border-radius:4px;border:1px solid var(--border);title:attr(data-name)}
  .clock{font-size:.72rem;color:var(--fg-dim)}
  @media(max-width:700px){main{grid-template-columns:1fr}#sidebar{display:none}}
</style>
</head>
<body>
<header>
  <span class="dot ok" id="eng-dot"></span>
  <h1>Novaforge AI Dev Interface</h1>
  <span class="badge">Phase 2</span>
  <span style="flex:1"></span>
  <span class="clock" id="clk"></span>
</header>
<main>
  <!-- ── Chat ─────────────────────────────────────────────────────────────── -->
  <div id="chat-pane">
    <div id="messages"></div>
    <div id="actions-row" class="actions-row"></div>
    <div id="input-area">
      <textarea id="user-input" placeholder="Ask ArbiterAI about Novaforge…" rows="1"></textarea>
      <button class="send-btn" onclick="sendMessage()">Send</button>
    </div>
  </div>
  <!-- ── Sidebar ───────────────────────────────────────────────────────────── -->
  <div id="sidebar">
    <div id="auth-banner">🔑 <b>API Token:</b> <span id="tok-display">—</span></div>
    <div class="sidebar-section">
      <div class="sidebar-hdr">AI Engine Health</div>
      <div class="stat-card"><div class="stat-val" id="ai-status">—</div><div class="stat-lbl">ArbiterEngine</div></div>
    </div>
    <div class="sidebar-section">
      <div class="sidebar-hdr">Resources <span id="res-ts" class="clock"></span></div>
      <div class="stat-card">
        <div style="font-size:.75rem;color:var(--fg-dim)">CPU</div>
        <div class="resource-bar"><div class="resource-fill" id="cpu-bar" style="width:0%"></div></div>
        <div class="stat-lbl" id="cpu-lbl">—</div>
      </div>
      <div class="stat-card">
        <div style="font-size:.75rem;color:var(--fg-dim)">Memory</div>
        <div class="resource-bar"><div class="resource-fill" id="mem-bar" style="width:0%"></div></div>
        <div class="stat-lbl" id="mem-lbl">—</div>
      </div>
      <div class="stat-card">
        <div style="font-size:.75rem;color:var(--fg-dim)">Disk</div>
        <div class="resource-bar"><div class="resource-fill" id="dsk-bar" style="width:0%"></div></div>
        <div class="stat-lbl" id="dsk-lbl">—</div>
      </div>
    </div>
    <div class="sidebar-section">
      <div class="sidebar-hdr">Theme</div>
      <div id="theme-swatch"></div>
    </div>
  </div>
</main>
<script>
// ── Config ──────────────────────────────────────────────────────────────────
const TOKEN = localStorage.getItem('nf_token') || prompt('Enter your API token:') || '';
if (TOKEN) localStorage.setItem('nf_token', TOKEN);
document.getElementById('tok-display').textContent = TOKEN ? TOKEN.slice(0,8) + '…' : '(none)';

const headers = {'Content-Type':'application/json','Authorization':'Bearer '+TOKEN};

// ── Helpers ──────────────────────────────────────────────────────────────────
function ts(){ return new Date().toISOString().slice(11,19); }
function setInterval2(fn, ms){ fn(); return setInterval(fn, ms); }

function addMsg(role, text){
  const el = document.getElementById('messages');
  const d = document.createElement('div');
  d.className = 'msg ' + role;
  d.textContent = text;
  el.appendChild(d);
  el.scrollTop = el.scrollHeight;
  return d;
}

// ── Clock ─────────────────────────────────────────────────────────────────────
setInterval(()=>{ document.getElementById('clk').textContent = new Date().toUTCString().slice(5,25)+' UTC'; },1000);

// ── Send message (SSE stream) ─────────────────────────────────────────────────
async function sendMessage(){
  const inp = document.getElementById('user-input');
  const prompt = inp.value.trim();
  if (!prompt) return;
  inp.value = '';
  addMsg('user', prompt);

  const aiDiv = addMsg('ai', '');
  let full = '';
  try {
    const url = '/ai/stream?prompt=' + encodeURIComponent(prompt);
    const evts = new EventSource(url + '&token=' + encodeURIComponent(TOKEN));
    evts.onmessage = e => {
      if (e.data === '[DONE]') { evts.close(); finaliseActions(full); return; }
      try { const d = JSON.parse(e.data); full += d.token || ''; aiDiv.textContent = full; }
      catch { full += e.data; aiDiv.textContent = full; }
      document.getElementById('messages').scrollTop = 9999;
    };
    evts.onerror = () => { evts.close(); if(!full) aiDiv.textContent = '[Connection error]'; };
  } catch(e) { aiDiv.textContent = '[Error: ' + e + ']'; }
}

// ── Action buttons (NF2-3) ───────────────────────────────────────────────────
async function generateActions(){
  const inp = document.getElementById('user-input');
  const prompt = inp.value.trim() || 'Generate next development actions for Novaforge';
  inp.value = '';
  const row = document.getElementById('actions-row');
  row.innerHTML = '<em style="color:var(--fg-dim);font-size:.78rem">Generating actions…</em>';
  try {
    const r = await fetch('/ai/actions', {method:'POST', headers, body:JSON.stringify({prompt, project:'Novaforge'})});
    const d = await r.json();
    row.innerHTML = '';
    (d.actions || []).forEach(a => {
      const btn = document.createElement('button');
      btn.className = 'action-btn';
      btn.textContent = a.title || a.type;
      btn.title = a.description || '';
      btn.onclick = () => executeAction(a);
      row.appendChild(btn);
    });
    if (!(d.actions||[]).length) row.innerHTML = '<em style="color:var(--fg-dim);font-size:.78rem">No actions generated.</em>';
  } catch(e) { row.innerHTML = '<em style="color:var(--danger)">Error: '+e+'</em>'; }
}

async function executeAction(action){
  addMsg('system', 'Executing: ' + (action.title || action.type) + '…');
  try {
    const r = await fetch('/ai/execute', {method:'POST', headers, body:JSON.stringify({action})});
    const d = await r.json();
    addMsg('system', 'Done: ' + JSON.stringify(d).slice(0,120));
  } catch(e) { addMsg('system', 'Error: '+e); }
}

// ── Health ───────────────────────────────────────────────────────────────────
async function loadHealth(){
  try {
    const r = await fetch('/ai/health', {headers});
    const d = await r.json();
    const ok = d.status === 'ok';
    document.getElementById('ai-status').textContent = ok ? 'Online' : (d.status||'?');
    document.getElementById('eng-dot').className = 'dot ' + (ok?'ok':'err');
  } catch { document.getElementById('ai-status').textContent = 'Unreachable'; document.getElementById('eng-dot').className = 'dot err'; }
}

// ── Resources (NF2-7) ────────────────────────────────────────────────────────
async function loadResources(){
  try {
    const r = await fetch('/ai/resources', {headers});
    const d = await r.json();
    function setBar(prefix, pct, label){
      document.getElementById(prefix+'-bar').style.width = pct+'%';
      document.getElementById(prefix+'-lbl').textContent = label;
    }
    if (d.cpu !== undefined) setBar('cpu', d.cpu.percent, d.cpu.percent.toFixed(1)+'%');
    if (d.memory) setBar('mem', d.memory.percent, (d.memory.used_gb||0).toFixed(1)+'/'+(d.memory.total_gb||0).toFixed(1)+' GB');
    if (d.disk) setBar('dsk', d.disk.percent, (d.disk.used_gb||0).toFixed(0)+'/'+(d.disk.total_gb||0).toFixed(0)+' GB');
    document.getElementById('res-ts').textContent = ts();
  } catch { document.getElementById('res-ts').textContent = '(unavailable)'; }
}

// ── Theme (NF2-4) ─────────────────────────────────────────────────────────────
async function loadTheme(){
  try {
    const r = await fetch('/ai/theme');
    const d = await r.json();
    const sw = document.getElementById('theme-swatch');
    sw.innerHTML = '';
    Object.entries(d).forEach(([k,v])=>{
      if(typeof v === 'string' && v.startsWith('#')){
        const s = document.createElement('div');
        s.className = 'swatch'; s.style.background = v; s.title = k+': '+v;
        sw.appendChild(s);
      }
    });
  } catch {}
}

// ── Keyboard shortcut ─────────────────────────────────────────────────────────
document.getElementById('user-input').addEventListener('keydown', e => {
  if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage(); }
});

function finaliseActions(fullReply){
  // If AI reply looks like it contains actions, offer generation
  if (fullReply.toLowerCase().includes('action') || fullReply.length > 200) {
    const row = document.getElementById('actions-row');
    const btn = document.createElement('button');
    btn.className = 'action-btn'; btn.textContent = '⚡ Generate Actions';
    btn.onclick = generateActions; row.appendChild(btn);
  }
}

// ── Init ─────────────────────────────────────────────────────────────────────
loadHealth(); loadResources(); loadTheme();
setInterval(loadHealth, 30000);
setInterval(loadResources, 10000);

addMsg('system', 'Novaforge AI Dev Interface ready — Phase 2');
</script>
</body>
</html>"""


# =============================================================================
# Application setup
# =============================================================================

if not _FASTAPI_OK:
    # Degrade gracefully so the module can be imported even without FastAPI
    app = None  # type: ignore[assignment]
else:
    app = FastAPI(
        title="Novaforge Remote Web Interface",
        description="AI-powered remote interface for the Novaforge game project.",
        version="2.0.0",
    )

    # ── AI manager singleton ──────────────────────────────────────────────────
    _ENGINE_URL = os.environ.get("ARBITER_ENGINE_URL", "http://127.0.0.1:8001")
    _ai: ArbiterAIManager | None = (
        ArbiterAIManager(engine_url=_ENGINE_URL, project="Novaforge")
        if _AI_OK else None
    )

    # ── Request models ────────────────────────────────────────────────────────

    class QueryRequest(BaseModel):
        prompt: str
        project: str = "Novaforge"
        history: list[dict] = []

    class ActionsRequest(BaseModel):
        prompt: str
        project: str = "Novaforge"

    class ExecuteRequest(BaseModel):
        action: dict

    class ContextFileRequest(BaseModel):
        path: str

    # =========================================================================
    # NF2-2 — Browser client
    # =========================================================================

    @app.get("/", response_class=HTMLResponse, include_in_schema=False)
    def root() -> HTMLResponse:
        """Serve the self-contained Novaforge AI Dev browser client.

        NF2-2
        """
        return HTMLResponse(content=_DASHBOARD_HTML, status_code=200)

    # =========================================================================
    # NF2-1 — AI endpoints
    # =========================================================================

    @app.post("/ai/query", dependencies=[Depends(_verify_token)])
    async def ai_query(req: QueryRequest) -> dict:
        """Single-turn AI query — returns the full reply as JSON.

        NF2-1
        """
        if _ai is None:
            return {"reply": "(ArbiterAI not available — check ArbiterEngine is running)"}
        reply = await asyncio.to_thread(_ai.query, req.prompt)
        return {"reply": reply or "", "project": req.project}

    @app.get("/ai/stream")
    async def ai_stream(
        prompt: str,
        token: str = "",
        request: Request = None,
    ) -> StreamingResponse:
        """SSE-streamed AI response — token-by-token.

        NF2-1, NF2-2
        Token can be passed as a query parameter for EventSource (which
        cannot set headers).
        """
        # Auth: accept token via query param (EventSource limitation)
        if token != _API_TOKEN:
            # Also check Authorization header for direct calls
            auth_header = request.headers.get("authorization", "") if request else ""
            if auth_header.replace("Bearer ", "").strip() != _API_TOKEN:
                raise HTTPException(status_code=401, detail="Invalid token")

        async def _generate() -> AsyncGenerator[str, None]:
            if _ai is None:
                yield "data: " + json.dumps({"token": "(ArbiterAI unavailable)"}) + "\n\n"
                yield "data: [DONE]\n\n"
                return

            # Run blocking AI call in a thread, simulate token streaming
            result: list[str] = [""]

            def _call() -> None:
                result[0] = _ai.query(prompt) or ""

            await asyncio.to_thread(_call)
            reply = result[0]

            # Stream word-by-word for a natural feel
            words = reply.split(" ")
            for i, word in enumerate(words):
                token_str = (word + (" " if i < len(words) - 1 else ""))
                yield "data: " + json.dumps({"token": token_str}) + "\n\n"
                await asyncio.sleep(0.01)

            yield "data: [DONE]\n\n"

        return StreamingResponse(
            _generate(),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "X-Accel-Buffering": "no",
            },
        )

    @app.post("/ai/actions", dependencies=[Depends(_verify_token)])
    async def ai_actions(req: ActionsRequest) -> dict:
        """Generate a list of executable AIActions for the given prompt.

        NF2-1, NF2-3
        """
        if _ai is None:
            return {"actions": [], "error": "ArbiterAI not available"}
        actions = await asyncio.to_thread(_ai.generate_actions, req.prompt)
        return {"actions": [vars(a) for a in actions], "project": req.project}

    @app.post("/ai/execute", dependencies=[Depends(_verify_token)])
    async def ai_execute(req: ExecuteRequest) -> dict:
        """Execute an AIAction dict against the Novaforge project.

        NF2-3
        """
        if _ai is None:
            return {"status": "error", "error": "ArbiterAI not available"}
        if AIAction is None:
            return {"status": "error", "error": "AIAction class not available"}
        try:
            action = AIAction(**req.action)
        except (TypeError, ValueError) as exc:
            raise HTTPException(status_code=422, detail=str(exc)) from exc
        result = await asyncio.to_thread(_ai.execute_action, action)
        return result

    @app.get("/ai/history", dependencies=[Depends(_verify_token)])
    def ai_history() -> dict:
        """Return the current in-memory conversation history.

        NF2-1
        """
        if _ai is None:
            return {"history": []}
        return {"history": list(getattr(_ai, "_memory", []))}

    @app.post("/ai/context/file", dependencies=[Depends(_verify_token)])
    async def ai_context_file(req: ContextFileRequest) -> dict:
        """Inject a file's contents into the AI conversation context.

        NF2-1
        """
        target = pathlib.Path(req.path)
        if not target.is_absolute():
            target = _NF_ROOT / req.path
        try:
            content = target.read_text(encoding="utf-8", errors="replace")
        except (OSError, ValueError) as exc:
            raise HTTPException(status_code=404, detail=str(exc)) from exc

        context_prompt = (
            f"[Context: file '{req.path}' ({len(content)} chars)]\n"
            f"```\n{content[:8000]}\n```"
        )
        if _ai:
            _ai._push_memory("user", context_prompt)  # noqa: SLF001
        return {"status": "ok", "path": req.path, "length": len(content)}

    # =========================================================================
    # NF2-4 — Theme
    # =========================================================================

    @app.get("/ai/theme")
    def ai_theme() -> dict:
        """Return the current Novaforge colour palette (ChatGPT dark by default).

        NF2-4
        """
        return dict(_THEME_CHATGPT)

    # =========================================================================
    # NF2-1 — Health
    # =========================================================================

    @app.get("/ai/health")
    async def ai_health() -> dict:
        """Check ArbiterEngine availability and return service health.

        NF2-1
        """
        import urllib.request as _req
        import urllib.error

        engine_url = _ENGINE_URL
        engine_ok = False
        try:
            with _req.urlopen(f"{engine_url}/health", timeout=3) as resp:
                data = json.loads(resp.read().decode())
                engine_ok = data.get("status") == "ok"
        except (urllib.error.URLError, Exception):
            pass

        return {
            "status":       "ok" if engine_ok else "degraded",
            "engine_url":   engine_url,
            "engine_ok":    engine_ok,
            "ai_available": _AI_OK,
            "ts":           datetime.datetime.utcnow().isoformat(),
        }

    # =========================================================================
    # NF2-7 — Resource monitoring
    # =========================================================================

    @app.get("/ai/resources", dependencies=[Depends(_verify_token)])
    def ai_resources() -> dict:
        """Return live CPU, memory, and disk usage statistics.

        Uses psutil if installed; gracefully returns a stub otherwise.

        NF2-7
        """
        if not _PSUTIL_OK:
            return {
                "available": False,
                "reason": "psutil not installed — run: pip install psutil",
            }
        return {
            "available": True,
            "ts": datetime.datetime.utcnow().isoformat(),
            "cpu": {
                "percent":      _psutil.cpu_percent(interval=0.1),
                "count_logical": _psutil.cpu_count(logical=True),
                "count_physical": _psutil.cpu_count(logical=False),
            },
            "memory": {
                "percent":   _psutil.virtual_memory().percent,
                "used_gb":   round(_psutil.virtual_memory().used   / 1024 ** 3, 2),
                "total_gb":  round(_psutil.virtual_memory().total  / 1024 ** 3, 2),
                "avail_gb":  round(_psutil.virtual_memory().available / 1024 ** 3, 2),
            },
            "disk": {
                "percent":   _psutil.disk_usage("/").percent,
                "used_gb":   round(_psutil.disk_usage("/").used  / 1024 ** 3, 1),
                "total_gb":  round(_psutil.disk_usage("/").total / 1024 ** 3, 1),
                "free_gb":   round(_psutil.disk_usage("/").free  / 1024 ** 3, 1),
            },
        }


# =============================================================================
# NF2-8 — Crash-protection supervisor
# =============================================================================

def _run_supervised(host: str, port: int, max_retries: int = 20) -> None:
    """Launch the uvicorn server with auto-restart on crash.

    NF2-8
    """
    import subprocess

    attempt = 0
    backoff = 2.0

    while attempt < max_retries:
        print(
            f"[Novaforge WebAPI] Starting server (attempt {attempt + 1}/{max_retries}) "
            f"at http://{host}:{port}"
        )
        cmd = [
            sys.executable, "-m", "uvicorn",
            "Projects.Novaforge.WebAPI.remote_api:app",
            "--host", host, "--port", str(port),
        ]
        proc = subprocess.run(cmd, check=False)
        if proc.returncode == 0:
            print("[Novaforge WebAPI] Server exited cleanly.")
            break
        attempt += 1
        print(
            f"[Novaforge WebAPI] Server crashed (code {proc.returncode}). "
            f"Restarting in {backoff:.0f}s…"
        )
        time.sleep(backoff)
        backoff = min(backoff * 1.5, 60.0)

    if attempt >= max_retries:
        print(f"[Novaforge WebAPI] Giving up after {max_retries} crash restarts.")
        sys.exit(1)


# =============================================================================
# NF2-6 — Entry point (LAN access on 0.0.0.0)
# =============================================================================

def main() -> None:
    """Entry point for running the Novaforge Remote Web Interface.

    NF2-6
    """
    import argparse

    parser = argparse.ArgumentParser(description="Novaforge Remote Web Interface")
    parser.add_argument("--host",       default="0.0.0.0",  help="Bind host (default: 0.0.0.0)")
    parser.add_argument("--port",       default=8006, type=int, help="Port (default: 8006)")
    parser.add_argument("--supervised", action="store_true",
                        help="NF2-8: wrap server in auto-restart supervisor loop")
    parser.add_argument("--ngrok",      action="store_true",
                        help="NF2-6: open an ngrok tunnel (requires pyngrok)")
    args = parser.parse_args()

    if not _FASTAPI_OK:
        print(
            "[Novaforge WebAPI] FastAPI / uvicorn not installed.\n"
            "Run: pip install fastapi uvicorn[standard]"
        )
        sys.exit(1)

    print(f"[Novaforge WebAPI] API token: {_API_TOKEN}")
    print(f"[Novaforge WebAPI] Dashboard:  http://{args.host}:{args.port}/")

    # NF2-6: optional ngrok tunnel
    if args.ngrok:
        try:
            from pyngrok import ngrok  # type: ignore[import]
            tunnel = ngrok.connect(args.port)
            print(f"[Novaforge WebAPI] ngrok public URL: {tunnel.public_url}")
        except ImportError:
            print("[Novaforge WebAPI] pyngrok not installed — run: pip install pyngrok")

    if args.supervised:
        _run_supervised(args.host, args.port)
    else:
        uvicorn.run(
            "Projects.Novaforge.WebAPI.remote_api:app",
            host=args.host,
            port=args.port,
            reload=False,
        )


if __name__ == "__main__":
    main()
